### ISSUE TITLE
"Cannot read property 'end' of null" when clicking on AirPlay device

### ISSUE THREAD

**Issue by Traktuner** [afaden/babelpod#15]
Hello,
when I select my AirPlay device, it says:
`switch_output: airplay_192.168.0.10_7000`
but nothing happens - no audio.
When I click on the next AirPlay device to try it out, the following happens:

```
switch_output: airplay_192.168.0.14_7000
inputStream FromVoid {
  _readableState: 
   ReadableState {
     objectMode: false,
     highWaterMark: 16384,
     buffer: BufferList { head: null, tail: null, length: 0 },
     length: 0,
     pipes: null,
     pipesCount: 0,
     flowing: null,
     ended: false,
     endEmitted: false,
     reading: false,
     sync: true,
     needReadable: false,
     emittedReadable: false,
     readableListening: false,
     resumeScheduled: false,
     destroyed: false,
     defaultEncoding: 'utf8',
     awaitDrain: 0,
     readingMore: false,
     decoder: null,
     encoding: null },
  readable: true,
  _events: {},
  _eventsCount: 0,
  _maxListeners: undefined }
outputStream ToVoid {
  _writableState: 
   WritableState {
     objectMode: false,
     highWaterMark: 16384,
     finalCalled: false,
     needDrain: false,
     ending: false,
     ended: false,
     finished: false,
     destroyed: false,
     decodeStrings: true,
     defaultEncoding: 'utf8',
     length: 0,
     writing: false,
     corked: 0,
     sync: true,
     bufferProcessing: false,
     onwrite: [Function: bound onwrite],
     writecb: null,
     writelen: 0,
     bufferedRequest: null,
     lastBufferedRequest: null,
     pendingcb: 0,
     prefinished: false,
     errorEmitted: false,
     bufferedRequestCount: 0,
     corkedRequestsFree: 
      { next: null,
        entry: null,
        finish: [Function: bound onCorkedFinish] } },
  writable: true,
  _events: {},
  _eventsCount: 0,
  _maxListeners: undefined }
/home/pi/node_airtunes/lib/rtsp.js:385
    this.socket.end(this.makeHead('TEARDOWN', '', di) + '\r\n');
                ^

TypeError: Cannot read property 'end' of null
    at Client.sendNextRequest (/home/pi/node_airtunes/lib/rtsp.js:385:17)
    at Client.teardown (/home/pi/node_airtunes/lib/rtsp.js:124:8)
    at AirTunesDevice.stop (/home/pi/node_airtunes/lib/device_airtunes.js:121:13)
    at cleanupCurrentOutput (/home/pi/babelpod/index.js:151:19)
    at Socket.<anonymous> (/home/pi/babelpod/index.js:202:5)
    at Socket.emit (events.js:180:13)
    at /home/pi/babelpod/node_modules/socket.io/lib/socket.js:528:12
    at process._tickCallback (internal/process/next_tick.js:112:11)
```

I installed it on my new Raspberry Pi Zero W, latest Raspbian Buster release and the setup as described on the official BabelPod page.

Any ideas what I can try?

Thank you!

**Comment by skip-sands** [comment]
I do have exactly  the same problem. @Traktuner did you find a solution?

**Comment by Traktuner** [comment]
Sadly not, it's still not working. Hope "afaden" comes back to this great project soon to help us with that ...

**Comment by skip-sands** [comment]
I wanted to try installing an older raspbian release as it seems he used a raspbian stretch release. Maybe that makes a difference?

**Comment by Traktuner** [comment]
I already tried that - with the Raspbian release from that time, but also same error ...
Also tried different node releases and different "Node-airtunes" forks, but same issue.
It would be really great, if someone who got it working (with a Raspbi Pi Zero W) could give us some hints how they got it working. Maybe I'm missing a point here ...

**Comment by larxene066** [comment]
Did anyone get anywhere with this? I've been racking my brain trying to figure this out
